 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/social_media", type: :request do
  
  # SocialMedium. As you add validations to SocialMedium, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SocialMedium.create! valid_attributes
      get social_media_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      social_medium = SocialMedium.create! valid_attributes
      get social_medium_url(social_medium)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_social_medium_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      social_medium = SocialMedium.create! valid_attributes
      get edit_social_medium_url(social_medium)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SocialMedium" do
        expect {
          post social_media_url, params: { social_medium: valid_attributes }
        }.to change(SocialMedium, :count).by(1)
      end

      it "redirects to the created social_medium" do
        post social_media_url, params: { social_medium: valid_attributes }
        expect(response).to redirect_to(social_medium_url(SocialMedium.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SocialMedium" do
        expect {
          post social_media_url, params: { social_medium: invalid_attributes }
        }.to change(SocialMedium, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post social_media_url, params: { social_medium: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested social_medium" do
        social_medium = SocialMedium.create! valid_attributes
        patch social_medium_url(social_medium), params: { social_medium: new_attributes }
        social_medium.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the social_medium" do
        social_medium = SocialMedium.create! valid_attributes
        patch social_medium_url(social_medium), params: { social_medium: new_attributes }
        social_medium.reload
        expect(response).to redirect_to(social_medium_url(social_medium))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        social_medium = SocialMedium.create! valid_attributes
        patch social_medium_url(social_medium), params: { social_medium: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested social_medium" do
      social_medium = SocialMedium.create! valid_attributes
      expect {
        delete social_medium_url(social_medium)
      }.to change(SocialMedium, :count).by(-1)
    end

    it "redirects to the social_media list" do
      social_medium = SocialMedium.create! valid_attributes
      delete social_medium_url(social_medium)
      expect(response).to redirect_to(social_media_url)
    end
  end
end
